[package]
name = "flint"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
blake3 = { version = "1.8.2", features = ["digest"] }
clap = "4.5.47"
directories = "6.0.0"
ed25519-dalek = { version = "=3.0.0-pre.0", features = ["pem", "pkcs8", "rand_core", "signature"] }
futures = "0.3.31"
hex = "0.4.3"
rand_core = { version = "0.9.3", features = ["os_rng"] }
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tar = "0.4.44"
temp-dir = "0.1.16"
walkdir = "2.5.0"
